name: firmware-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytest
  - pytest-xdist
  - pyserial
  - ruff
  - pyyaml
  - pip:
      - rerun-sdk
      - halo
      - colorama
