name: firmware-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytest
  - pytest-xdist
  - pyserial
  - ruff
  - pyyaml
  - jinja2
  - pip:
      - pydantic
      - rerun-sdk
      - halo
      - colorama
      - scancode-toolkit
      - typecode-libmagic
      - tree-sitter
      - tree-sitter-rust
      - jinja-lsp
      - eel

