[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  # Required to find embassy's boot2 loader if boot2 feature is used
  "-C", "link-arg=-Tlink-rp.x",
]
