[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = "/Users/daparker/gh/firmware/tools/runner.sh"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  # Required to find embassy's boot2 loader if boot2 feature is used
  "-C", "link-arg=-Tlink-rp.x",
  "--remap-path-prefix", "firmware=/Users/daparker/gh/firmware",
]
