# Peripherals Configuration to generate initializers.

[[peripheral]]
name = "Max17048"
bus = "i2c"
init = { init = true, probe = true }

[[peripheral]]
name = "Ina219"
bus = "i2c"
init = { reset = true, init = true, probe = true }

[[peripheral]]
name = "Vl53l0x"
bus = "i2c"
init = { reset = true, init = true, probe = true }

[[peripheral]]
name = "Ws2812"
has_pio = true
