
[alias]
check-host = "check --workspace --all-targets"
check-mcu = "check --workspace --bins --lib --target=thumbv6m-none-eabi --exclude=host_cli --exclude=host_fs --exclude=tool_common"

[target.thumbv6m-none-eabi]
runner = "tools/runner.sh"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Tlink-rp.x",
]

[env]
DEFMT_LOG = "debug"

