
[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Tlink-rp.x",
  "-C", "link-arg=-Lprojects/cat_detector",
  "--remap-path-prefix", "firmware=/Users/daparker/gh/firmware",
]

[env]
DEFMT_LOG = "info"
