[package]
name = "controller"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
model = { path = "../model" }
platform = { path = "../platform" }
tracing-defmt = { version = "0.1.2", optional = true }
defmt = { version = "0.3", optional = true }
peripheral = { path = "../peripheral" }
embassy-sync = "0.6.2"
sequential-storage = "3.0.0"
embedded-storage-async = "0.4.1"
heapless = "0.8.0"
embedded-io = "0.6.0"
minicbor = "0.20.0"
embassy-futures = "0.1.0"
embedded-cli = "0.2.1"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-storage = "0.3"


[target.'cfg(all(target_arch = "arm", target_os = "none"))'.dependencies]
embassy-time = { version = "0.4.0", features = ["defmt"] }
defmt = "0.3"
cortex-m = { version = "0.7" }

[target.'cfg(not(all(target_arch = "arm", target_os = "none")))'.dependencies]
embassy-time = { version = "0.4.0", features = ["std"] }

[dev-dependencies]
peripheral = { path = "../peripheral", features = ["mock"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

[target.'cfg(not(all(target_arch = "arm", target_os = "none")))'.dev-dependencies]
embassy-executor = { version = "0.7.0", features = ["arch-std", "executor-thread", "task-arena-size-1048576"] }

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
rinja = "0.2"
code_gen = { path = "../tools/code_gen" }

[features]
core1 = ["peripheral/core1"]
motor-core = ["core1", "peripheral/motor-core"]
sensors-core = ["core1", "peripheral/sensors-core"]
tracing = [
    "platform/tracing",
    "peripheral/tracing",
    "dep:tracing-defmt",
    "dep:defmt",
]
